### ISSUE TITLE
Internet e WIFI

### ISSUE THREAD

**Issue by chicobentojr** [cades-ifrn/minicurso-react-native-gdg-natal#1]
Para se conectar, tente abrir o seguinte link:

https://autenticacao-cnat:6082/php/uid.php?vsys=1&rule=0&url=https://google.com

Para WIFI, procure por `eduroam`.

O usuário é: `minicursodiatinfcnat`

E a senha é: `ifrn.2018`

**Comment by felipemfp** [comment]
Muito útil. :smiley_cat:
